name: Unit tests

on:
  push:
    branches:
      - master
    paths:
      - src/**
      - tests/**
      - cmake/**

jobs:
  build_tests_and_run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: configure
      run: cmake -S ${{github.workspace}}
                 -B ${{github.workspace}}/build
                 -DECB_PARAM_DEBUG=OFF
                 -DECB_PARAM_TESTS=ON

    - name: build
      run: cmake --build ${{github.workspace}}/build

    - name: run tests
      working-directory: ${{github.workspace}}/build
      run: ctest
